name: Fetch Book Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # This line means the action will run everyday at 08:00 in the UK

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scrape script
        run: python assets/get_books.py
        
      - name: Commit and push if it's changed
        run: |
          git add .
          git diff
          git config --global user.email "r.mcminds@gmail.com"
          git config --global user.name "rmcminds"
          git commit -am "Book data update" || echo "No changes to commit"
          git push
